trigger:
  batch: true
  branches:
    include:
      - main

variables:
  tag: '$(Build.BuildId)'
  branch: '$(Build.SourceBranchName)'
  sparkVersion: '3.2.0'


pool: 'stratus-build-pool.u'


stages:
  - stage: Build_and_Publish_Maven_and_Python_Artifact
    jobs:
      - job: BuildPublishMavenArtifact
        steps:
          - task: Maven@3
            displayName: "Build project with maven"
            inputs:
              mavenPomFile: "pom.xml"
              mavenOptions: "-Xmx3072m"
              javaHomeOption: "path"
              jdkVersionOption: "1.8"
              jdkArchitectureOption: "x64"
              jdkDirectory: "/usr/lib/jvm/java-8-openjdk-amd64"
              publishJUnitResults: true
              testResultsFiles: "**/surefire-reports/TEST-*.xml"
              goals: "deploy"
